## Importing put data and getting the data

In [176]:
import numpy as np
import pandas as pd 
ges_results=pd.read_csv('../Data/ges_results.csv')

### Data to work with

In [177]:
data=ges_results.copy()

### Data has 1055 rows and 7 columns, with only 1054 rows filled appropriately

In [178]:

data.shape  #(1055,7)
data.describe()

,Timestamp,Score,Matric. No:,Level,Department:,Faculty:,Group No:
count,1054,1054,1054,1051,1054,1054,1054
unique,503,22,1027,21,135,71,93
top,3/15/2024 17:54:46,19 / 25,237780,100,Medicine and Surgery,Science,52
freq,10,126,4,902,58,307,57

### All the Columns available are 7 in number

In [179]:
print(f"There are {data.columns.shape[0]} columns in all which are {data.columns.values}")

There are 7 columns in all which are ['Timestamp' 'Score' 'Matric. No:' 'Level' 'Department:' 'Faculty:'
 'Group No:']

In [180]:
data.head()

,Timestamp,Score,Matric. No:,Level,Department:,Faculty:,Group No:
0,3/15/2024 17:41:50,20 / 25,236482,100,Microbiology,Science,41
1,3/15/2024 17:42:58,10 / 25,236311,100,Chemistry,Science,52
2,3/15/2024 17:44:39,17 / 25,236391,100,Geology,Science,27
3,3/15/2024 17:45:21,15 / 25,236608,100,Statistics,Science,57
4,3/15/2024 17:45:26,12 / 25,238141,200,Nursing,Clinical science,43

### Members of Group 38 and what they filled their Group as in the Google form

In [181]:
Group_38=data.loc[data['Group No:']=='38']
Group_38
weird=data.loc[data['Group No:']=='No 38']
weird
another_weird=data.loc[data['Group No:']=='Group 38']
another_weird
display('Total of all memebers ')
Group_38.count()+weird.count()+another_weird.count()
display('Concatenation of all Group 38 members ')
full_group_38=display(pd.concat([Group_38,weird,another_weird],keys=['Used 38 as Group','Used No 38 as Group','Used Group 38 as Group']))

'Total of all memebers '

'Concatenation of all Group 38 members '

                                      Timestamp    Score Matric. No:  \
Used 38 as Group       14    3/15/2024 17:46:52  22 / 25      235292
                       94    3/15/2024 17:49:39  22 / 25      235244
                       109   3/15/2024 17:50:09  20 / 25      235234
                       201   3/15/2024 17:51:59  21 / 25      235192
                       242   3/15/2024 17:52:32  16 / 25      237412
                       344   3/15/2024 17:53:25  22 / 25      235295
                       366   3/15/2024 17:53:37  16 / 25      235271
                       383   3/15/2024 17:53:43  21 / 25      235214
                       440   3/15/2024 17:54:10  23 / 25      235249
                       447   3/15/2024 17:54:11  20 / 25      235197
                       448   3/15/2024 17:54:11  19 / 25      235182
                       449   3/15/2024 17:54:11  22 / 25      235231
                       461   3/15/2024 17:54:14  19 / 25      235209
                       462   3/15/2024 17:54:14  19 / 25      235167
                       498   3/15/2024 17:54:24  19 / 25      235213
                       500   3/15/2024 17:54:25  19 / 25      235211
                       527   3/15/2024 17:54:33  24 / 25      237402
                       546   3/15/2024 17:54:37  19 / 25      235205
                       548   3/15/2024 17:54:37  20 / 25      230953
                       567   3/15/2024 17:54:43  18 / 25      235180
                       635   3/15/2024 17:54:54  23 / 25      235235
                       673   3/15/2024 17:55:00  23 / 25      235189
                       869   3/15/2024 17:56:23  21 / 25      235260
                       917   3/15/2024 17:56:45  19 / 25      235202
                       922   3/15/2024 17:56:47  20 / 25      235181
                       924   3/15/2024 17:56:47  16 / 25      235172
                       1020  3/15/2024 17:58:44  19 / 25      235267
Used No 38 as Group    644   3/15/2024 17:54:55  22 / 25      235287
Used Group 38 as Group 404   3/15/2024 17:53:57  15 / 25      235219
                       441   3/15/2024 17:54:10  22 / 25      235221
                       493   3/15/2024 17:54:22  20 / 25      235228

                                  Level                  Department:  \
Used 38 as Group       14           100        Medicine and Surgery
                       94           100         Medicine and surgery
                       109   100 level         Medicine and Surgery
                       201          100         Medicine and surgery
                       242          100        Medicine and Surgery
                       344          100                        MBBS
                       366          100        Medicine and Surgery
                       383          100        Medicine and surgery
                       440    100 Level        Medicine and Surgery
                       447          100         medicine and surgery
                       448          100        Medicine and Surgery
                       449          100        Medicine and Surgery
                       461          100        Medicine and Surgery
                       462          200        Medicine and Surgery
                       498          100        MEDICINE AND SURGERY
                       500          100        Medicine and surgery
                       527          200         Medicine and Surgery
                       546          100        Medicine and Surgery
                       548          100        Medicine and Surgery
                       567          200        Medicine and surgery
                       635          200                         MBBS
                       673          100         Medicine and Surgery
                       869          100                         MBBS
                       917          100         Medicine and surgery
                       922     100level        Medicine and surgery
                       924          100        Medicine and surgery
                       1020         200         Medicine and surgery
Used No 38 as Group    644          100        Medicine and Surgery
Used Group 38 as Group 404          200        Medicine and Surgery
                       441          100        Medicine and Surgery
                       493   200 Level   Medicine and Surgery (MBBS)

                                          Faculty: Group No:
Used 38 as Group       14       Clinical Sciences         38
                       94        Clinical sciences        38
                       109      Clinical Sciences         38
                       201       Clinical sciences        38
                       242      Clinical Sciences         38
                       344      Clinical Sciences         38
                       366      Clinical Sciences         38
                       383      Clinical Sciences         38
                       440       Clinical Sciences        38
                       447       clinical sciences        38
                       448      Clinical Sciences         38
                       449      Clinical Sciences         38
                       461      Clinical Sciences         38
                       462      Clinical sciences         38
                       498    COLLEGE OF MEDICINE         38
                       500      Clinical sciences         38
                       527       Clinical Sciences        38
                       546       Clinical science         38
                       548      Clinical sciences         38
                       567      Clinical sciences         38
                       635   BASIC MEDICAL SCIENCE        38
                       673       Clinical sciences        38
                       869       Clinical Sciences        38
                       917       Clinical sciences        38
                       922      Clinical Sciences         38
                       924       Clinical sciences        38
                       1020      Clinical sciences        38
Used No 38 as Group    644      Clinical Sciences      No 38
Used Group 38 as Group 404      Clinical Sciences   Group 38
                       441       Clinical Sciences  Group 38
                       493    College of Medicine   Group 38

### Scores of Students in GROUP 38 in descending order

In [184]:
all_group_38=pd.concat([Group_38,weird,another_weird])
all_group_38.sort_values(by='Score',ascending=False,kind='mergesort')
all_group_38.reset_index(drop=True)

,Timestamp,Score,Matric. No:,Level,Department:,Faculty:,Group No:
0,3/15/2024 17:46:52,22 / 25,235292,100,Medicine and Surgery,Clinical Sciences,38
1,3/15/2024 17:49:39,22 / 25,235244,100,Medicine and surgery,Clinical sciences,38
2,3/15/2024 17:50:09,20 / 25,235234,100 level,Medicine and Surgery,Clinical Sciences,38
3,3/15/2024 17:51:59,21 / 25,235192,100,Medicine and surgery,Clinical sciences,38
4,3/15/2024 17:52:32,16 / 25,237412,100,Medicine and Surgery,Clinical Sciences,38
5,3/15/2024 17:53:25,22 / 25,235295,100,MBBS,Clinical Sciences,38
6,3/15/2024 17:53:37,16 / 25,235271,100,Medicine and Surgery,Clinical Sciences,38
7,3/15/2024 17:53:43,21 / 25,235214,100,Medicine and surgery,Clinical Sciences,38
8,3/15/2024 17:54:10,23 / 25,235249,100 Level,Medicine and Surgery,Clinical Sciences,38
9,3/15/2024 17:54:11,20 / 25,235197,100,medicine and surgery,clinical sciences,38
10,3/15/2024 17:54:11,19 / 25,235182,100,Medicine and Surgery,Clinical Sciences,38
11,3/15/2024 17:54:11,22 / 25,235231,100,Medicine and Surgery,Clinical Sciences,38
12,3/15/2024 17:54:14,19 / 25,235209,100,Medicine and Surgery,Clinical Sciences,38
13,3/15/2024 17:54:14,19 / 25,235167,200,Medicine and Surgery,Clinical sciences,38
14,3/15/2024 17:54:24,19 / 25,235213,100,MEDICINE AND SURGERY,COLLEGE OF MEDICINE,38
15,3/15/2024 17:54:25,19 / 25,235211,100,Medicine and surgery,Clinical sciences,38
16,3/15/2024 17:54:33,24 / 25,237402,200,Medicine and Surgery,Clinical Sciences,38
17,3/15/2024 17:54:37,19 / 25,235205,100,Medicine and Surgery,Clinical science,38
18,3/15/2024 17:54:37,20 / 25,230953,100,Medicine and Surgery,Clinical sciences,38
19,3/15/2024 17:54:43,18 / 25,235180,200,Medicine and surgery,Clinical sciences,38
20,3/15/2024 17:54:54,23 / 25,235235,200,MBBS,BASIC MEDICAL SCIENCE,38
21,3/15/2024 17:55:00,23 / 25,235189,100,Medicine and Surgery,Clinical sciences,38
22,3/15/2024 17:56:23,21 / 25,235260,100,MBBS,Clinical Sciences,38
23,3/15/2024 17:56:45,19 / 25,235202,100,Medicine and surgery,Clinical sciences,38
24,3/15/2024 17:56:47,20 / 25,235181,100level,Medicine and surgery,Clinical Sciences,38
25,3/15/2024 17:56:47,16 / 25,235172,100,Medicine and surgery,Clinical sciences,38
26,3/15/2024 17:58:44,19 / 25,235267,200,Medicine and surgery,Clinical sciences,38
27,3/15/2024 17:54:55,22 / 25,235287,100,Medicine and Surgery,Clinical Sciences,No 38
28,3/15/2024 17:53:57,15 / 25,235219,200,Medicine and Surgery,Clinical Sciences,Group 38
29,3/15/2024 17:54:10,22 / 25,235221,100,Medicine and Surgery,Clinical Sciences,Group 38
30,3/15/2024 17:54:22,20 / 25,235228,200 Level,Medicine and Surgery (MBBS),College of Medicine,Group 38

### Total number of students in GROUP 38

In [186]:
all_group_38.count()

print(f"There are {all_group_38.shape[0]} students in GROUP 38")

There are 31 students in GROUP 38

### Medicial Students scores in descending order

In [191]:
pd.set_option('display.max_rows',150)
medicine_students=data.loc[data['Department:'].isin(['ME','med','Mb','MB','Med','Mbbs ','MBBS ','Medicine and Surgery ','medicine and surgery ','Medicine And Surgery ','Medicine and surgery ','Medicine and Surgery','Medicine and Surgery (MBBS)','Mbbs','medicine and surgery','MEDICINE AND SURGERY','MBBS','Medicine and surgery','Medicine And Surgery','MEDICINE AND SURGERY ','MEDICINE AND SURGERY(Mbbs)','Mbbs ','medicine and surgery '])]

med_scores=medicine_students.sort_values(by='Score',ascending=False,kind='mergesort')
med_student_scores=med_scores.copy()
med_student_scores.head()
med_student_scores.reset_index(drop=True)

,Timestamp,Score,Matric. No:,Level,Department:,Faculty:,Group No:
0,3/15/2024 17:56:00,25 / 25,235248,100 LEVEL,MEDICINE AND SURGERY,CLINICAL SCIENCES,39/40
1,3/15/2024 17:59:09,25 / 25,237406,100,Medicine and surgery,Clinical sciences,36
2,3/15/2024 17:48:19,24 / 25,235193,100,Medicine and Surgery,Clinical sciences,MBBS GES 39/40
3,3/15/2024 17:51:16,24 / 25,235184,100,Medicine and surgery,Clinical sciences,37
4,3/15/2024 17:52:57,24 / 25,237405,100,MBBS,Clinical Science,36
5,3/15/2024 17:54:33,24 / 25,237402,200,Medicine and Surgery,Clinical Sciences,38
6,3/15/2024 17:55:57,24 / 25,235296,100,MBBS,Clinical sciences,39/40
7,3/15/2024 17:56:26,24 / 25,235263,100,Medicine and Surgery,Clinical Sciences,39/40
8,3/15/2024 17:57:03,24 / 25,235284,100,MBBS,Clinical science,36
9,3/15/2024 17:58:30,24 / 25,235233,100,Medicine and Surgery,Clinical Science,36
10,3/15/2024 17:46:51,23 / 25,235255,100 level,Medicine And Surgery,Clinical sciences,37
11,3/15/2024 17:48:33,23 / 25,235291,235291,Medicine and Surgery,College of Medicine,36
12,3/15/2024 17:50:15,23 / 25,235215,100 Level,Medicine and Surgery,Clinical Sciences,37
13,3/15/2024 17:50:30,23 / 25,235217,100 level,Medicine and surgery,Clinical sciences,37
14,3/15/2024 17:53:02,23 / 25,237762,100,Medicine and Surgery,Clinical Sciences,36
15,3/15/2024 17:53:55,23 / 25,235290,100,Medicine and Surgery,Clinical science,Group 36
16,3/15/2024 17:54:10,23 / 25,235249,100 Level,Medicine and Surgery,Clinical Sciences,38
17,3/15/2024 17:54:35,23 / 25,235242,100L,Medicine and surgery,Clinical sciences,39/40
18,3/15/2024 17:54:49,23 / 25,235268,100,Medicine and Surgery,Clinical Sciences,39/40
19,3/15/2024 17:54:54,23 / 25,235235,200,MBBS,BASIC MEDICAL SCIENCE,38
20,3/15/2024 17:55:00,23 / 25,235189,100,Medicine and Surgery,Clinical sciences,38
21,3/15/2024 17:55:28,23 / 25,235208,100l,Medicine and Surgery,Clinical Science,36
22,3/15/2024 17:56:11,23 / 25,235286,100,Medicine and Surgery,Clinical sciences,39/40
23,3/15/2024 17:56:31,23 / 25,235210,100l,Medicine and Surgery,Clinical sciences,36
24,3/15/2024 17:57:06,23 / 25,235250,100 Level,Medicine and Surgery,Clinical Sciences,39/40
25,3/15/2024 17:57:09,23 / 25,235259,100,Medicine and Surgery,Clinical Science,39/40
26,3/15/2024 17:59:03,23 / 25,235265,100,Medicine and Surgery,Clinical Sciences,39
27,3/15/2024 17:46:52,22 / 25,235292,100,Medicine and Surgery,Clinical Sciences,38
28,3/15/2024 17:48:29,22 / 25,235266,100,Medicine and Surgery,Clinical Sciences,37
29,3/15/2024 17:49:32,22 / 25,237763,100,MBBS,Clinical science,37
30,3/15/2024 17:49:39,22 / 25,235244,100,Medicine and surgery,Clinical sciences,38
31,3/15/2024 17:50:05,22 / 25,235230,100,MBBS,CLINICAL SCIENCES,36
32,3/15/2024 17:51:56,22 / 25,235196,100,Medicine and Surgery,Clinical Sciences,37
33,3/15/2024 17:52:09,22 / 25,230788,100,Medicine and surgery,Clinical Sciences,36
34,3/15/2024 17:52:23,22 / 25,235194,100,Medicine and Surgery,Clinical Sciences,37
35,3/15/2024 17:53:25,22 / 25,235295,100,MBBS,Clinical Sciences,38
36,3/15/2024 17:53:36,22 / 25,237410,100,MBBS,Clinical Science,37
37,3/15/2024 17:54:10,22 / 25,235221,100,Medicine and Surgery,Clinical Sciences,Group 38
38,3/15/2024 17:54:11,22 / 25,235231,100,Medicine and Surgery,Clinical Sciences,38
39,3/15/2024 17:54:31,22 / 25,235246,100,Medicine and Surgery,Clinical sciences,39/40
40,3/15/2024 17:54:55,22 / 25,235287,100,Medicine and Surgery,Clinical Sciences,No 38
41,3/15/2024 17:55:00,22 / 25,230428,100l,MBBS,Clinical Science,37
42,3/15/2024 17:55:19,22 / 25,235230,100,MBBS,CLINICAL SCIENCES,36
43,3/15/2024 17:56:35,22 / 25,235224,100,Medicine and surgery,Clinical sciences,37
44,3/15/2024 17:58:51,22 / 25,235201,100,Medicine and Surgery,Clinical sciences,39
45,3/15/2024 17:47:11,21 / 25,235279,100,Medicine and Surgery,Clinical Sciences,Group 37
46,3/15/2024 17:49:43,21 / 25,235177,100,Medicine and Surgery,Clinical Science,37
47,3/15/2024 17:51:59,21 / 25,235192,100,Medicine and surgery,Clinical sciences,38
48,3/15/2024 17:52:48,21 / 25,237767,100,Medicine and Surgery,Clinical Sciences,36
49,3/15/2024 17:52:52,21 / 25,235278,100,Medicine and Surgery,Clinical Sciences,39/40
50,3/15/2024 17:53:43,21 / 25,235284,100,MBBS,Clinical science,36
51,3/15/2024 17:53:43,21 / 25,235214,100,Medicine and surgery,Clinical Sciences,38
52,3/15/2024 17:54:14,21 / 25,235269,100 level,Medicine and surgery,Clinical sciences,39/40
53,3/15/2024 17:54:28,21 / 25,237408,100,Medicine and Surgery,Clinical Sciences,39/40
54,3/15/2024 17:54:29,21 / 25,235204,100,Medicine and surgery,Clinical sciences,39
55,3/15/2024 17:54:34,21 / 25,235285,100,Medicine and surgery,Clinical science,39
56,3/15/2024 17:55:15,21 / 25,235279,100,Medicine and Surgery,Clinical Sciences,Group 37
57,3/15/2024 17:55:51,21 / 25,235188,100,Medicine and Surgery,Clinical Sciences,39/40
58,3/15/2024 17:56:23,21 / 25,235260,100,MBBS,Clinical Sciences,38
59,3/15/2024 17:56:28,21 / 25,235191,100,Medicine and Surgery,Clinical Sciences,39
60,3/15/2024 17:57:18,21 / 25,235252,100 Level,Medicine and surgery,Clinical sciences,39/40
61,3/15/2024 17:58:07,21 / 25,235174,100 level,Medicine and surgery,Clinical science,39/40
62,3/15/2024 17:59:09,21 / 25,237413,100 level,Medicine and Surgery,Clinical Sciences,39
63,3/15/2024 17:59:10,21 / 25,235258,100,Medicine and Surgery,Clinical Sciences,36
64,3/15/2024 17:50:09,20 / 25,235234,100 level,Medicine and Surgery,Clinical Sciences,38
65,3/15/2024 17:50:21,20 / 25,235239,100,Medicine and Surgery,Clinical sciences,37
66,3/15/2024 17:51:21,20 / 25,235282,100,Medicine and Surgery,Clinical Sciences,37
67,3/15/2024 17:52:27,20 / 25,237765,100,Medicine and Surgery,Clinical sciences,36
68,3/15/2024 17:54:11,20 / 25,235197,100,medicine and surgery,clinical sciences,38
69,3/15/2024 17:54:22,20 / 25,235228,200 Level,Medicine and Surgery (MBBS),College of Medicine,Group 38
70,3/15/2024 17:54:37,20 / 25,230953,100,Medicine and Surgery,Clinical sciences,38
71,3/15/2024 17:54:46,20 / 25,235176,100,Medicine and Surgery,Clinical Sciences,Ges 101 39/40
72,3/15/2024 17:55:16,20 / 25,213221,100,Medicine and surgery,Clinical science,39
73,3/15/2024 17:56:42,20 / 25,235273,100,MEDICINE AND SURGERY,Clinical Sciences,39/40
74,3/15/2024 17:56:47,20 / 25,235181,100level,Medicine and surgery,Clinical Sciences,38
75,3/15/2024 17:57:20,20 / 25,235216,100 level,Medicine and Surgery,Clinical Sciences,39
76,3/15/2024 17:57:57,20 / 25,235223,100,Medicine and Surgery,Clinical Sciences,39/40
77,3/15/2024 17:58:43,20 / 25,237414,100,MBBS,Clinical Science,39
78,3/15/2024 17:49:53,19 / 25,235190,100,MBBS,Clinical sciences,37
79,3/15/2024 17:52:14,19 / 25,235257,100,Medicine and surgery,Clinical science,37
80,3/15/2024 17:53:38,19 / 25,235179,100,Medicine and surgery,Clinical sciences,36
81,3/15/2024 17:54:11,19 / 25,235182,100,Medicine and Surgery,Clinical Sciences,38
82,3/15/2024 17:54:14,19 / 25,235209,100,Medicine and Surgery,Clinical Sciences,38
83,3/15/2024 17:54:14,19 / 25,235167,200,Medicine and Surgery,Clinical sciences,38
84,3/15/2024 17:54:24,19 / 25,235213,100,MEDICINE AND SURGERY,COLLEGE OF MEDICINE,38
85,3/15/2024 17:54:25,19 / 25,235211,100,Medicine and surgery,Clinical sciences,38
86,3/15/2024 17:54:37,19 / 25,235198,100,MEDICINE AND SURGERY,CLINICAL SCIENCE,37
87,3/15/2024 17:54:37,19 / 25,235205,100,Medicine and Surgery,Clinical science,38
88,3/15/2024 17:54:42,19 / 25,235247,100,Medicine and surgery,Clinical sciences,36
89,3/15/2024 17:54:59,19 / 25,235253,100,medicine and surgery,clinical sciences,37
90,3/15/2024 17:55:04,19 / 25,235171,100,Medicine and Surgery,Clinical Sciences,39
91,3/15/2024 17:55:38,19 / 25,235275,100,Medicine and Surgery,Clinical Sciences,37
92,3/15/2024 17:55:54,19 / 25,235186,100,Medicine And Surgery,Clinical Science,39
93,3/15/2024 17:56:45,19 / 25,235202,100,Medicine and surgery,Clinical sciences,38
94,3/15/2024 17:58:10,19 / 25,237403,100,Medicine and Surgery,Clinical Sciences,39/40
95,3/15/2024 17:58:44,19 / 25,235267,200,Medicine and surgery,Clinical sciences,38
96,3/15/2024 17:46:15,18 / 25,235206,100,Medicine and surgery,Clinical sciences,36
97,3/15/2024 17:52:28,18 / 25,235220,100,Mbbs,Clinical science,36
98,3/15/2024 17:53:06,18 / 25,235200,100,Medicine and Surgery,Clinical Sciences,37
99,3/15/2024 17:53:18,18 / 25,237764,100,Medicine and Surgery,Clinical Sciences,37
100,3/15/2024 17:53:52,18 / 25,237401,100,Medicine and surgery,Clinical sciences,37
101,3/15/2024 17:54:28,18 / 25,235272,100lvl,Medicine and Surgery,Clinical Sciences,39
102,3/15/2024 17:54:43,18 / 25,235180,200,Medicine and surgery,Clinical sciences,38
103,3/15/2024 17:56:15,18 / 25,235199,100,Medicine and Surgery,Clinical Sciences,36
104,3/15/2024 17:56:38,18 / 25,235294,100 Level,MBBS,Clinical science,36
105,3/15/2024 17:56:45,18 / 25,237404,100,Medicine and Surgery,Clinical Sciences,37
106,3/15/2024 17:57:48,18 / 25,235203,100,Medicine and surgery,Clinical science,39
107,3/15/2024 17:58:26,18 / 25,235288,100,Medicine and Surgery,Clinical Sciences,39/40
108,3/15/2024 17:59:33,18 / 25,237400,100,Medicine and Surgery,Clinical sciences,39/40
109,3/15/2024 17:51:19,17 / 25,235212,200,MBBS,Clinical sciences,36
110,3/15/2024 17:53:30,17 / 25,235274,100,MEDICINE AND SURGERY,Clinical Sciences,36
111,3/15/2024 17:54:35,17 / 25,235227,100 level,Medicine and Surgery,Clinical sciences,39/40
112,3/15/2024 17:54:37,17 / 25,235238,100,Medicine and Surgery,Clinical sciences,37
113,3/15/2024 17:54:40,17 / 25,235218,200,Medicine and Surgery,Clinical Sciences,39
114,3/15/2024 17:55:03,17 / 25,235262,100,MEDICINE AND SURGERY,CLINICAL SCIENCES,39/40
115,3/15/2024 17:55:58,17 / 25,237415,100,Medicine and Surgery,Clinical Sciences,36
116,3/15/2024 17:55:59,17 / 25,235226,200,Medicine and surgery,Clinical science,1
117,3/15/2024 17:57:10,17 / 25,235281,100,Medicine and Surgery,Clinical sciences,36
118,3/15/2024 17:58:11,17 / 25,235169,100,Medicine and surgery,Clinical sciences,36
119,3/15/2024 17:59:01,17 / 25,235173,100,Medicine and surgery,Clinical science,39
120,3/15/2024 17:48:39,16 / 25,235251,100,Medicine and Surgery,Clinical Sciences,36
121,3/15/2024 17:52:32,16 / 25,237412,100,Medicine and Surgery,Clinical Sciences,38
122,3/15/2024 17:53:37,16 / 25,235271,100,Medicine and Surgery,Clinical Sciences,38
123,3/15/2024 17:53:44,16 / 25,235195,100 level,Medicine and surgery,Clinical sciences,37
124,3/15/2024 17:54:02,16 / 25,235183,100L,Medicine and Surgery,Clinical science,37
125,3/15/2024 17:56:47,16 / 25,235172,100,Medicine and surgery,Clinical sciences,38
126,3/15/2024 17:57:26,16 / 25,237409,100,Medicine and surgery,Clinical science,39/40
127,3/15/2024 17:57:55,16 / 25,235170,100,MBBS,Clinical science,36
128,3/15/2024 17:58:57,16 / 25,235185,100,Medicine and surgery,Clinical science,39
129,3/15/2024 17:50:13,15 / 25,235254,100,Medicine and Surgery,Clinical Sciences,36
130,3/15/2024 17:50:31,15 / 25,235277,100 level,Medicine and surgery,Clinical sciences,37
131,3/15/2024 17:53:47,15 / 25,235178,100,Medicine And Surgery,Clinical sciences,37
132,3/15/2024 17:53:57,15 / 25,235219,200,Medicine and Surgery,Clinical Sciences,Group 38
133,3/15/2024 17:55:39,15 / 25,237769,100,Medicine and Surgery,Clinical science,36
134,3/15/2024 17:56:46,15 / 25,235241,100,Medicine and Surgery,Clinical science,39/40
135,3/15/2024 17:57:02,15 / 25,237766,100,Medicine and Surgery,College of medicine,39
136,3/15/2024 17:57:54,15 / 25,220710,100,Medicine and surgery,Clinical Science,36
137,3/15/2024 17:58:13,15 / 25,235289,100,Medicine and Surgery,Clinical sciences,36
138,3/15/2024 17:53:24,14 / 25,235270,100,Medicine and surgery,Clinical science,37
139,3/15/2024 17:55:25,14 / 25,235229,100,Medicine and Surgery,Clinical Sciences,39
140,3/15/2024 17:56:28,13 / 25,157307,100,Medicine and surgery,Clinical Sciences,36
141,3/15/2024 17:57:36,12 / 25,237768,200,Medicine and Surgery,Clinical Sciences,39