#### Loading our Packages

In [12]:
import pandas as pd 
import numpy as np
import seaborn as sb
from sklearn.datasets import load_diabetes

#### Working with the Diabetes Data from sklearn datasets

In [13]:
diabetes=load_diabetes()
diabetes.keys()
diabetes_data=pd.DataFrame(diabetes.data,columns=diabetes.feature_names)

#### Showing some informations about the dataset

In [14]:
diabetes_data.head(n=10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504

In [15]:
diabetes_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [16]:
diabetes_data.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [26]:
diabetes_data.shape

(442, 10)

In [30]:

#Creating a DataFrame with Random Values 
random_df=pd.DataFrame(np.random.rand(20,10))
random_df

,0,1,2,3,4,5,6,7,8,9
0,0.470340,0.217862,0.407852,0.137025,0.370649,0.710011,0.222271,0.011554,0.399121,0.507577
1,0.073131,0.754945,0.047508,0.315631,0.737651,0.543623,0.293525,0.763595,0.598397,0.403872
2,0.495995,0.733479,0.786065,0.286389,0.914892,0.548328,0.703162,0.811369,0.158808,0.513584
3,0.294313,0.115116,0.559246,0.969879,0.560826,0.425506,0.178263,0.919528,0.877550,0.552344
4,0.863267,0.628600,0.072245,0.101929,0.834405,0.751765,0.451141,0.263995,0.106580,0.547382
5,0.654956,0.381377,0.276875,0.709573,0.317103,0.250094,0.354921,0.547038,0.945108,0.773736
6,0.393336,0.434571,0.924431,0.759067,0.590368,0.219259,0.915724,0.225440,0.550555,0.364126
7,0.638197,0.619175,0.229068,0.275468,0.337503,0.994527,0.204561,0.475955,0.723645,0.814699
8,0.887664,0.589055,0.521974,0.647362,0.703062,0.799857,0.085283,0.202217,0.231665,0.068077
9,0.211635,0.972263,0.327460,0.684752,0.328892,0.423886,0.499557,0.838941,0.487181,0.520747
10,0.765823,0.888176,0.159917,0.997248,0.675108,0.332601,0.224569,0.831789,0.004570,0.904580
11,0.828950,0.686156,0.721001,0.500681,0.165340,0.481331,0.431192,0.984242,0.439987,0.167924
12,0.259117,0.483380,0.107997,0.705058,0.164196,0.356828,0.937803,0.667988,0.442990,0.260240
13,0.281362,0.403824,0.687323,0.682885,0.233006,0.562749,0.206815,0.913035,0.677632,0.320678
14,0.419413,0.160586,0.502678,0.636104,0.346127,0.171085,0.016360,0.376935,0.255652,0.303908
15,0.321087,0.370782,0.725302,0.486751,0.792770,0.405155,0.390908,0.845538,0.269305,0.961372
16,0.852990,0.900360,0.855988,0.935847,0.967740,0.798993,0.538657,0.807798,0.765667,0.885018
17,0.243708,0.004231,0.084450,0.420680,0.461467,0.544121,0.429145,0.054266,0.141521,0.556006
18,0.330614,0.674579,0.114614,0.101645,0.796366,0.070928,0.728327,0.138315,0.193666,0.611155
19,0.856287,0.307684,0.610888,0.755487,0.767755,0.679740,0.121065,0.058741,0.410214,0.233890

In [37]:
random_df.isnull().sum()
diabetes_data.value_counts('sex')

sex
-0.044642    235
 0.050680    207
Name: count, dtype: int64

#### Statistical Measures

In [45]:
diabetes_data.groupby('sex').mean()
diabetes_data.count()
diabetes_data.mean()
diabetes_data.std()
diabetes_data.min()
diabetes_data.max()
diabetes_data.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

#### Exploring Pandas DataFrame

In [48]:
### Dropping data
random_df.drop(index=0,axis=0) ##Removing the first row (axis=0 is for rows while axis=1 is for columns)

,0,1,2,3,4,5,6,7,8,9
1,0.073131,0.754945,0.047508,0.315631,0.737651,0.543623,0.293525,0.763595,0.598397,0.403872
2,0.495995,0.733479,0.786065,0.286389,0.914892,0.548328,0.703162,0.811369,0.158808,0.513584
3,0.294313,0.115116,0.559246,0.969879,0.560826,0.425506,0.178263,0.919528,0.877550,0.552344
4,0.863267,0.628600,0.072245,0.101929,0.834405,0.751765,0.451141,0.263995,0.106580,0.547382
5,0.654956,0.381377,0.276875,0.709573,0.317103,0.250094,0.354921,0.547038,0.945108,0.773736
6,0.393336,0.434571,0.924431,0.759067,0.590368,0.219259,0.915724,0.225440,0.550555,0.364126
7,0.638197,0.619175,0.229068,0.275468,0.337503,0.994527,0.204561,0.475955,0.723645,0.814699
8,0.887664,0.589055,0.521974,0.647362,0.703062,0.799857,0.085283,0.202217,0.231665,0.068077
9,0.211635,0.972263,0.327460,0.684752,0.328892,0.423886,0.499557,0.838941,0.487181,0.520747
10,0.765823,0.888176,0.159917,0.997248,0.675108,0.332601,0.224569,0.831789,0.004570,0.904580
11,0.828950,0.686156,0.721001,0.500681,0.165340,0.481331,0.431192,0.984242,0.439987,0.167924
12,0.259117,0.483380,0.107997,0.705058,0.164196,0.356828,0.937803,0.667988,0.442990,0.260240
13,0.281362,0.403824,0.687323,0.682885,0.233006,0.562749,0.206815,0.913035,0.677632,0.320678
14,0.419413,0.160586,0.502678,0.636104,0.346127,0.171085,0.016360,0.376935,0.255652,0.303908
15,0.321087,0.370782,0.725302,0.486751,0.792770,0.405155,0.390908,0.845538,0.269305,0.961372
16,0.852990,0.900360,0.855988,0.935847,0.967740,0.798993,0.538657,0.807798,0.765667,0.885018
17,0.243708,0.004231,0.084450,0.420680,0.461467,0.544121,0.429145,0.054266,0.141521,0.556006
18,0.330614,0.674579,0.114614,0.101645,0.796366,0.070928,0.728327,0.138315,0.193666,0.611155
19,0.856287,0.307684,0.610888,0.755487,0.767755,0.679740,0.121065,0.058741,0.410214,0.233890

In [52]:
random_df.iloc[2] ##iloc returns the values for the rows (index mentioned)
random_df.loc[2]
random_df.iloc[:,-1]

0     0.507577
1     0.403872
2     0.513584
3     0.552344
4     0.547382
5     0.773736
6     0.364126
7     0.814699
8     0.068077
9     0.520747
10    0.904580
11    0.167924
12    0.260240
13    0.320678
14    0.303908
15    0.961372
16    0.885018
17    0.556006
18    0.611155
19    0.233890
Name: 9, dtype: float64

In [53]:
random_df.corr()

,0,1,2,3,4,5,6,7,8,9
0,1.000000,0.245684,0.213591,0.132126,0.253305,0.440339,-0.251471,-0.156160,-0.122911,0.006812
1,0.245684,1.000000,-0.043206,0.006834,0.289857,0.130045,0.281649,0.428767,-0.085268,0.198573
2,0.213591,-0.043206,1.000000,0.368735,0.155479,0.046736,0.045616,0.251737,0.230889,-0.125039
3,0.132126,0.006834,0.368735,1.000000,-0.092646,-0.188949,-0.120603,0.401864,0.348492,0.023226
4,0.253305,0.289857,0.155479,-0.092646,1.000000,0.157468,0.084680,-0.120779,-0.312975,0.317760
5,0.440339,0.130045,0.046736,-0.188949,0.157468,1.000000,-0.346067,-0.089747,0.110719,0.003248
6,-0.251471,0.281649,0.045616,-0.120603,0.084680,-0.346067,1.000000,0.049853,-0.068670,0.046992
7,-0.156160,0.428767,0.251737,0.401864,-0.120779,-0.089747,0.049853,1.000000,0.323135,0.223221
8,-0.122911,-0.085268,0.230889,0.348492,-0.312975,0.110719,-0.068670,0.323135,1.000000,0.092154
9,0.006812,0.198573,-0.125039,0.023226,0.317760,0.003248,0.046992,0.223221,0.092154,1.000000